name: paz
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  watch_it: ^1.7.0
  dio: ^5.9.0
  pocketbase: ^0.23.0+1
  just_audio: ^0.10.5
  audio_session: ^0.2.2
  google_fonts: ^6.3.1
  mesh_gradient: ^1.3.8
  flutter_animate: ^4.5.2
  dotenv: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  lints: ^5.1.1
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - env/dev.env
    - assets/audio/
